@startuml nombre

class Personaje
class CuboDeAceite
class Vida 
class Bigote 
class Martillo
class Vida
class Plataforma
class Escalera
class Nivel
class Obstaculo 
class Enemigo
class BarrilesAzules
class BarrilFire
class Jugador
class Colision
class Sombrero
class Animacion

class Jugador{
-nombre
-VidasRestantes
-NivelActual
-puntajeTotal
+iniciarPartida()
+perderVida()
+reiniciarJuego()
}

class Puntaje{
-puntos
+sumar()
}

class Martillo{
+destruirEnemigo
}

class BarrilExplosivo{
+explotar()
}

class Bonus{
+daraPuntos()
}

class MotorJuego{
+iniciar()
+actualizar()
}

class Barriles{
+rodar()
}

class DonkeyKong  {
-Vida vida(3)
+saltar()
+daño lanzabarril(daño)
}

class Mario {
-Vida vida(3)
-Puntaje
+saltar()
+usarMartillo()
+subirEscalera()
}

class Pauline {
+pedir ayuda()
}
class Fireball{
+mover()
+morir()
}

class Spark {
+morir()
+moverElectrico()
}

Mario --> Personaje
DonkeyKong --> Personaje
Pauline --> Personaje
Fireball --> Personaje
Spark --> Personaje
Fireball --> Enemigo
Spark --> Enemigo
DonkeyKong --> Enemigo
Fireball "many" o-- "1" CuboDeAceite

DonkeyKong *--Fuerza
DonkeyKong "i" o-- "many" Barriles
DonkeyKong "i" o-- "many" BarrilesAzules
DonkeyKong "i" o-- "many"BarrilFire
DonkeyKong "i" o-- "many" BarrilExplosivo
DonkeyKong o--Plataformas
DonkeyKong --> Pauline

Barriles --> Mario : golpea
BarrilesAzules --> Mario :golpea
BarrilFire --> Mraio : golpea
BarrilExplosivo --> Mario : golpea

MotorJuego "i" --> "many" Nivel


Mario "i" o--"0..1" Martillo
Mario o--Escaleras
Mario *--Sombrero
Mario *--Bigote
Mario "i" *-- "3" Vida 
Mario "i" *-- "many" Salto
Mario "i" *-- "many" Colision
Mario "i" -- "1" Pauline :rescata
Mario --> Escalera
Mario --> Plataforma
Mario --> Bonus

Pauline *--Sombrero 
Pauline *--Bolso 
Pauline *--Paraguas

Colision --> Enemigo
Colision --> Obstaculo

Jugador "i" -- "i" Mario
Jugador "i" -- "i" Puntaje

Nivel "i" *-- Enemigo
Sonido --> MotorJuego
Animacion --> Personaje

@enduml
